### ISSUE TITLE
Nächste Schritte

### ISSUE THREAD

**Issue by franke94** [jnhck/time_microservice#1]
Hallo zusammen, 

ich habe jetzt einfach mal die Issues-Sektion gewählt, um zu kommunizieren. Können wir natürlich auch auf Projects machen, wie euch das lieber ist. 

Also der Service sollte ja so funktionieren, wie er jetzt ist, habe ihn mal lokal ausprobiert. 

Was ist euch mal noch anschauen könnt ist der Zugriff auf Web-APIs. Zum Beispiel habe ich mal mit dieser ein bisschen rumgespielt: http://worldtimeapi.org/pages/examples
Damit lässt sich auch das Problem mit den Zeitzonen lösen.

Wenn wir später noch anspruchsvollere Services bauen wollen, dann müssen wir sowieso auf externe APIs zugreifen. 

Probiert einfach mal ein bisschen rum, wenn ihr Fragen habt gerne melden, dann versuche ich die zu beantworten. 

Viel Spaß 

Simon

**Comment by jnhck** [comment]
Hi,

ich habe den Microservice jetzt mal mit der WorldTimeAPI umgesetzt, die ist aber leider sehr langsam. Esdauert teilweise mehrere Sekunden bis es eine Antwort gibt. Falls das später noch einmal wichtig werden sollte, könnte ich natürlich noch weitere WebAPIs ausprobieren, und schauen, ob welche dabei sind, bei denen die Anfragen schneller beantwortet werden. 

Ich habe bei der Umsetzung auf das node package Axios zurückgegriffen, weil ich ausprobieren wollte wie sich das mit npm & Docker verhält. Man kann zum Glück einfach "npm install" über das Dockerfile ausführen lassen.

Wenn ich jetzt mithilfe des Dockerfiles ein Image erstelle, sind die Container, die ich davon instanziiere immer ausführbar. Sie geben also direkt immer eine Uhrzeit zurück (genaueres dazu in der Readme). Grundsätzlich könnte man es natürlich auch so implementieren, dass einfach nur die Shell geöffnet wird und wir selbst dann die Befehle darüber ausführen könnten.

Ich würde die Issue jetzt an dieser Stelle schließen. Anschließend kann man in der "Organisation" (studienprojekt-sdp), die ich hier über GitHub erstellt habe, weiter diskutieren. Die braucht man anscheinend für die CI/CD Funktionen von GitHub.

Jan
